apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtodo-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microtodo-ui
  template:
    metadata:
      labels:
        app: microtodo-ui
    spec:
      containers:
      - name: microtodo-ui
        image: lucktodoappacr2025.azurecr.io/microtodoui:v4
        ports:
        - containerPort: 80

