apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microtodo-ui-ingress
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: ui.shineluck.shop
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: microtodo-ui
              port: 
                number: 80
