name: "Build and Push UI Docker Image to ACR"
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest
    
    env:
      ACR_NAME: lucktodoappacr2025                         # ðŸ‘ˆ your actual ACR name
      IMAGE_NAME: microtodoui                             # ðŸ‘ˆ image name
      IMAGE_TAG: v5                                      # ðŸ‘ˆ image tagging
      RESOURCE_GROUP: dev-todoapp-rglav                   # ðŸ‘ˆ same RG where ACR is
      LOCATION: Central India                             # ðŸ‘ˆ your ACR region
      ACR_LOGIN_SERVER: lucktodoappacr2025.azurecr.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      # Login to Azure using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: e56aba2e-309d-4313-8091-e641c4c5c43b
          tenant-id: 8810bad7-7f76-4bba-8b17-d6d297d7bdd7
          subscription-id: 2a238ca4-a95b-43d2-846c-1618b53c6203
          
      - name: Azure CLI - Login to ACR
        run: |
          az acr login --name $ACR_NAME

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          
     # Tag Image to ACR
      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      # Push image to ACR
      - name: Push Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      # Optional: Print image name
      - name: Show pushed image name
        run: echo " Image pushed successfully:$ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG"    
